name: Gradle PR CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 23
      uses: actions/setup-java@v2
      with:
        java-version: 23
        distribution: 'zulu'
        cache: gradle
    - name: Build with Gradle
      run: ./gradlew build